services:
  emby-in-one:
    build:
      context: .
      args:
        VERSION: v1.4.0
    container_name: emby-in-one
    ports:
      - "8096:8096"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
